title: Graphics Demos
description: ...
baseurl: "/"
#color_scheme: dark
color_scheme: light_blue
footer_content: ""
url: "https://pmarsceill.github.io"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
